; list menu ID's
PCPOKEMONLISTMENU  EQU $00
MOVESLISTMENU      EQU $01
PRICEDITEMLISTMENU EQU $02
ITEMLISTMENU       EQU $03
SPECIALLISTMENU    EQU $04

MONSTER_NAME  EQU 1
MOVE_NAME     EQU 2
; ???_NAME    EQU 3
ITEM_NAME     EQU 4
PLAYEROT_NAME EQU 5
ENEMYOT_NAME  EQU 6
TRAINER_NAME  EQU 7

INIT_ENEMYOT_LIST    EQU 1
INIT_BAG_ITEM_LIST   EQU 2
INIT_OTHER_ITEM_LIST EQU 3
INIT_PLAYEROT_LIST   EQU 4
INIT_MON_LIST        EQU 5
